[package]
name = "transmitter"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "1.0.0"
panic-halt = "1.0.0"
rp235x-hal = { version = "0.2.0", features = ["critical-section-impl", "rt"] }
